# Generated by Django 3.1 on 2020-09-14 14:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('home', '0008_homepage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitewide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_tracking_code', models.TextField(blank=True, help_text='Tags <script> ARE necessary')),
                ('footer_tracking_code', models.TextField(blank=True, help_text='Tags <script> ARE necessary')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favicon', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('social_image', models.ForeignKey(blank=True, help_text='Social Open Graph Image will be used when no Main Image is defined', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FontItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('font_url', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to='home.sitewide')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
