# Generated by Django 3.1 on 2020-08-30 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailimages', '0022_uploadedimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogIndexPage',
            new_name='CaseIndexPage',
        ),
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='CasePage',
        ),
        migrations.RenameModel(
            old_name='BlogPageGalleryImage',
            new_name='CasePageGalleryImage',
        ),
    ]
