# Generated by Django 3.1 on 2020-08-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200830_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='casepage',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
